parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - crowdsecurity/nginx-logs
scenarios:
    - "./scenarios/crowdsecurity/basic-anomaly-detection.yaml"
postoverflows:
    - ""
log_file: basic-anomaly-detection.log
log_type: nginx
ignore_parsers: true
